name: Test Dotfiles

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run Ubuntu tests
      run: ./tests/run-tests.sh --ubuntu

  test-alpine:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Run Alpine tests
      run: ./tests/run-tests.sh --alpine

  test-scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Test script syntax
      run: |
        bash -n setup.sh
        bash -n sync.sh
        bash -n tests/test-suite.sh
        bash -n tests/run-tests.sh
      
    - name: Test help commands
      run: |
        ./setup.sh --help
        ./sync.sh help
        ./tests/run-tests.sh --help
        
    - name: Validate repository structure
      run: |
        test -f setup.sh
        test -f sync.sh
        test -d config/nvim
        test -d config/tmux
        test -d docs
        test -f docs/cheatsheet.md
        test -f docs/nvchad-guide.md
        test -f docs/tmux-guide.md